require('mapping')
require('which-key-bindings')
require('nvim_lsp')
require('plugin-config')
require('plugin_config/autopairs')
require('plugin_config/cmp')
require('plugin_config/dap')
require('plugin_config/indentblankline')
require('plugin_config/lsp_saga')
require('plugin_config/orgmode')
-- require('plugin_config/ufo')
